version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Pytest Tests
          command: |
            pip install --upgrade pip
            pip3 install -r requirements.txt
            pytest
            
workflows:
  build-and-test:
    jobs:
      - aws-ecr/build-and-push-image:
          region: ${AWS_REGION}
          repo: ${AWS_ECR_ACCOUNT_URL}/${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BUILD_NUM}